export const APP_FEATURE=[
    {
        id:"1",
        title:"Tailored Just for you",
        description:"Get inteview questions and model answers based on your role, experience, and specific focus areas."
    },
    {
        id:"2",
        title:"Learn At Your Own Pace",
        description:"Expand answers only when you're ready. Dive deeper into any concept instantly with AI-Powered detailed explanations."
    },
    {
        id:"3",
        title:"Capture Your Insights",
        description:"Add perosnal notes to any questions and pin important ones to the top -  making your learning more organizaed and impactful."
    },
    {
        id:"4",
        title:"Understand the 'WHY' Behind Answers ",
        description:"Beyond just answers - unlock detailed explanations generated by AI, helping you truly master each topic."
    },
    {
        id:"5",
        title:"Save, Organize, and Revisit",
        description:"Early save your interview sets, organizae them neatly in your dashboard and pick up your preparation right where you have left off."
    },
]

export const CARD_BG=[
    {id:1, bgcolor:'yellow'},
    {id:2, bgcolor:'cyan'},
    {id:3, bgcolor:'brown'},
    {id:4, bgcolor:'black'},
    {id:5, bgcolor:'orange'},
    {id:6, bgcolor:'green'},
    {id:7, bgcolor:'blue'},
    {id:8, bgcolor:'magenta'},
    {id:9, bgcolor:'purple'},
    {id:10, bgcolor:'pink'},
]